language: cpp
os:
- linux
- osx
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - cmake
    - python3.5
    - python3.5-dev
    - libboost-filesystem-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libbz2-dev
    - liblzma-dev
    - libpthread-stubs0-dev
    - wget
    - zlib1g-dev
install:
- if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then sudo apt-add-repository ppa:ubuntu-toolchain-r/test
  -y && sudo apt-get update && sudo apt-get install g++-5 -y && export CC=$(which
  gcc-5) CXX=$(which g++-5) && sudo rm /usr/bin/python3 && sudo ln -s $(which python3.5) /usr/bin/python3 &&
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && sudo python3.5 get-pip.py; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update >/dev/null && brew install
  zlib curl samtools bzip2 xz > /dev/null && export ZLIB_PATH=$(ls /usr/local/Cellar/zlib/*/lib/libz.a)
  LZMA_PATH=$(ls /usr/local/Cellar/xz/*/lib/liblzma.a); fi
- if [[ ! $(which python3) ]]; then python3(){ python $@; }; fi
- tar czf ../rnaseqc.$TRAVIS_TAG.full_source.tar.gz $TRAVIS_BUILD_DIR && mv ../rnaseqc.$TRAVIS_TAG.full_source.tar.gz $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/francois-a/rnaseq-utils rnaseq && cd rnaseq && git
  checkout f1c6a5677bbca465ea1edd06c2293a5d1078a18b && cd ..
- mv test_data/Makefile.$TRAVIS_OS_NAME Makefile
- "mkdir -p ~/.config/matplotlib && echo 'backend\t:\tAgg' > ~/.config/matplotlib/matplotlibrc"
- sudo python3 -m pip install --user --upgrade pip setuptools
- sudo python3 -m pip install --user numpy
- sudo python3 -m pip install --user -e ./python/
- sudo python3 -m pip install --user --force-reinstall --upgrade matplotlib
- make
before_script:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew install git-lfs; fi
- git lfs install
- git lfs pull
script:
- sudo bash -c "PYTHONPATH=$(pwd) make test"
before_deploy:
- gzip -c rnaseqc > rnaseqc.$TRAVIS_TAG.$TRAVIS_OS_NAME.gz
- if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then rm rnaseqc.*.full_source.tar.gz; fi
deploy:
  provider: releases
  api_key:
    secure: Q4Fy2TeDcQTbkmoGOK2fEBu1FhUQ+OHJs/nRlWdk6gPQrpZ7pF7DGcHQ+vwnO4P3f7RAzWN/3rvZK2kGobrMsTwijptMmN3lpE4rjCex9hiohPKzVzMZh+wjz+NlyTWApNkTXCwVh5rtn4Gv74V47vw9GMyrMWhznOChAhVlK0RX3iDMurq8wWaeOjbtCHjIpJRMV1HGke49I3t4cSj4nIPFg79M998D/PYA+An14dzk13BEH4oTiBIHIBDlfG2pnl0+l0KZTWJm9yyBTyVYaMbBrjCPwqhYERrdA7dHBs8D6k9rbMtvQKKS94k/uMs8shTcIpq3gjkC8O4yONf/TiiIpf07y5Ad4mR9kPZ9k5nKGHUgTRG3ml9WU73UOItjMiBvylHmRnGlO5bGjPlBxuNxG5FfzvL1AH+01tARS7h5MddX0PBz3X7buYXAPqNZC1cpnjBrlxpAB736yvtVB04N2rP6smSvioM+ZfxaBy5kYTm5HS18OSb4L7gKRCkCNf+u5snWabU8xGlpY+2AXyBd92DB5740/fIjFnSeIiLJuwm6pFwiOA/6UF5aW/jjCR/D+V8EzoFEaINN9OzdgFABXmJGcIomQZ9b2wxbGOI6X+MqU8kPVkP7o59QwywiMnYzGwtprGLik1TkYKVjIZA08l2lMQN6fGNEgHnvplQ=
  file: rnaseqc*.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: broadinstitute/rnaseqc
    tags: true
