language: cpp
os:
- linux
- osx
osx_image: xcode12
dist: bionic
addons:
  apt:
    packages:
    - cmake
    - libboost-filesystem-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libbz2-dev
    - liblzma-dev
    - libpthread-stubs0-dev
    - wget
    - zlib1g-dev
install:
- if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then sudo apt-add-repository ppa:ubuntu-toolchain-r/test
  -y && sudo apt-get update && sudo apt-get install g++-5 -y && export CC=$(which
  gcc-5) CXX=$(which g++-5) && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && sudo
  python3 get-pip.py; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update >/dev/null && brew install
  zlib curl samtools bzip2 xz > /dev/null && export ZLIB_PATH=$(ls /usr/local/Cellar/zlib/*/lib/libz.a)
  LZMA_PATH=$(ls /usr/local/Cellar/xz/*/lib/liblzma.a); fi
- if [[ ! $(which python3) ]]; then python3(){ python $@; }; fi
- tar czf ../rnaseqc.$TRAVIS_TAG.full_source.tar.gz $TRAVIS_BUILD_DIR && mv ../rnaseqc.$TRAVIS_TAG.full_source.tar.gz
  $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/francois-a/rnaseq-utils rnaseq && cd rnaseq && git
  checkout f1c6a5677bbca465ea1edd06c2293a5d1078a18b && cd ..
- mv test_data/Makefile.$TRAVIS_OS_NAME Makefile
- "mkdir -p ~/.config/matplotlib && echo 'backend\t:\tAgg' > ~/.config/matplotlib/matplotlibrc"
- sudo python3 -m pip install --user --upgrade pip setuptools
- sudo python3 -m pip install --user numpy
- sudo python3 -m pip install --user -e ./python/
- sudo python3 -m pip install --user --force-reinstall --upgrade matplotlib
- make
before_script:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew install git-lfs; fi
- git lfs install
- git lfs pull
script:
- sudo bash -c "PYTHONPATH=$(pwd) make test"
before_deploy:
- gzip -c rnaseqc > rnaseqc.$TRAVIS_TAG.$TRAVIS_OS_NAME.gz
- if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then rm rnaseqc.*.full_source.tar.gz; fi
deploy:
  provider: releases
  api_key:
    secure: GpWsjTlzdTtwqUw7GKLi3xcZI4dC+Sseb2oJvm8E16IgWFhuDsvLeqQ2nGqnsnrgMvVUmvg23OwsbPHwx6ir/Vgb1zwZYn8TNsScwRDdXqYRrTq8t7GvGitiuPQeOCXnN4Hn/a+v1DsbSGm5KuMLwQuLPDNTOPpqtuHDSLUX/GlJuTjX50O1/I2wVfT9oyldWddxmcJA3gHcnt0hDVXeqdFY6y+ZiGm34iNLisP7QofJw+qwAnbbeHk1Nm52ZyLwShA3lr+VXqknI+UMj2DcayedAfTvhLLm4IeEW0XQEVbz+nhknUObyqPpqNdGnqHcX25Igdd35Yo1ksmpTNV2ASKF9byQM0S9spmX/FQG5ZaE9Ey8sgv/RmONtEL5yTBAzlPmin9P3sqv7HGNyTBw3CmNs1BqwNqqQ5zKt7QPuO9orVyEsBJyC4wTxUmUfubAhPQCG/Qz/+eL3YeHcFPD2uXVSMZAEYarYxh95KQBIUdrHAXbIbEgMYUezbVX31jDk+B/U0WTXH5LrbptkiLXFeilID8giBrGZ9C5ZiKiyQXOJQj98BfNfpgGh5uKnAqAjgY7CarB0Y0erO+ggiGZqj+RqoZxSbDqWokmmtxw0H+XieOJ2yGX4sqB7CiTOQGXCSASeEYHvb9tBRpH7G/xxeOQyVzQdNy8Th62SC6oVBs=
  file: rnaseqc*.gz
  file_glob: true
  on:
    repo: getzlab/rnaseqc
    tags: true
  skip_cleanup: true
