language: cpp
os:
- linux
- osx
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - cmake
    - python3.5
    - python3.5-dev
    - libboost-filesystem-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libbz2-dev
    - liblzma-dev
    - libpthread-stubs0-dev
    - wget
    - zlib1g-dev
install:
- if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then sudo apt-add-repository ppa:ubuntu-toolchain-r/test
  -y && sudo apt-get update && sudo apt-get install g++-5 -y && export CC=$(which
  gcc-5) CXX=$(which g++-5) && sudo rm /usr/bin/python3 && sudo ln -s $(which python3.5) /usr/bin/python3 &&
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && sudo python3.5 get-pip.py; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update >/dev/null && brew install
  zlib curl samtools bzip2 xz > /dev/null && export ZLIB_PATH=$(ls /usr/local/Cellar/zlib/*/lib/libz.a)
  LZMA_PATH=$(ls /usr/local/Cellar/xz/*/lib/liblzma.a); fi
- if [[ ! $(which python3) ]]; then python3(){ python $@; }; fi
- tar czf ../rnaseqc.$TRAVIS_TAG.full_source.tar.gz $TRAVIS_BUILD_DIR && mv ../rnaseqc.$TRAVIS_TAG.full_source.tar.gz $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/francois-a/rnaseq-utils rnaseq && cd rnaseq && git
  checkout f1c6a5677bbca465ea1edd06c2293a5d1078a18b && cd ..
- mv test_data/Makefile.$TRAVIS_OS_NAME Makefile
- "mkdir -p ~/.config/matplotlib && echo 'backend\t:\tAgg' > ~/.config/matplotlib/matplotlibrc"
- sudo python3 -m pip install --user --upgrade pip setuptools
- sudo python3 -m pip install --user numpy
- sudo python3 -m pip install --user pandas pyBigWig bx-python agutil scipy
- sudo python3 -m pip install --user --force-reinstall --upgrade matplotlib
- make
before_script:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew install git-lfs; fi
- git lfs install
- git lfs pull
script:
- sudo bash -c "PYTHONPATH=$(pwd) make test"
before_deploy:
- gzip -c rnaseqc > rnaseqc.$TRAVIS_TAG.$TRAVIS_OS_NAME.gz
- if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then rm rnaseqc.*.full_source.tar.gz; fi
deploy:
  provider: releases
  api_key:
    secure: X8Jfw9SOYDFVxYKVV4C+aUVXYpDSRVxIdIGhNL9Wfe91iGJ2eSyT4o6+wfkH5HmSCHZYebpjN+iw+/JJ+0HZYlPQER/6Uit6EwB63sjwbh8lc5/PTNQhtxN5K9RFFtJD8FssfLNVqLEN+LjEUmKmOJECrgdRH2w5AbP3O0FfKj55pY9Saw+JNCOsnzgE6DMs2wyl0yAWfK6Ft9BpilJ2jU/Eyp+mPBAuyONbJTlX+fgJlAhiHA/B068Xsy28GQnyFWp/Z+tEl7SJZic3RW6Vd/1zU/4UwpMDIm5eNPxf/g8wP4GPZidDWfeRiL2EHU0QgieWV1S0NPEHT4ZJslchf2++nzSbiFYgOXQHao8349HU6enDjQISEKMoNH0/Miqlf0ls6uA+e1qkRZHcPtTmO9lcd1rS7GKDF1TVv4oCXNFhMibUQ153Mn/ibgkWAEhm9wkUBx32p4jjXERVMDnVV+jyhhqxBtCAqdcrBWlcNSiOgZCHy+rGOuO2jxtu8T/I67WtI49NBFyb1uLz/7Eqtp3vyjYrUFxP3LBOfY5wC7JKAcNd/Uyl2+Y6vyzvTsjvq7JWJcmEs00SwDG6H4G1d490Ut2Z8focFHlrsK3ljdGH99QYIskKEWYG30Jgt7T4cyu3OjYa1V+sSrifDq5cpTAIBtVdmW5jBA1k6vH+7ak=
  file: rnaseqc*.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: broadinstitute/rnaseqc
    tags: true
